[workspace]
resolver = "3"
members = ["crates/tussle-cli", "crates/tussle-core"]

[workspace.package]
version = "0.0.1-alpha.1"
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/defi-failure/tussle"
homepage = "https://github.com/defi-failure/tussle"
publish = false

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
